// Code generated by MockGen. DO NOT EDIT.
// Source: cars_grpc.pb.go

// Package carsapi is a generated GoMock package.
package carsapi

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCarsServiceClient is a mock of CarsServiceClient interface.
type MockCarsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCarsServiceClientMockRecorder
}

// MockCarsServiceClientMockRecorder is the mock recorder for MockCarsServiceClient.
type MockCarsServiceClientMockRecorder struct {
	mock *MockCarsServiceClient
}

// NewMockCarsServiceClient creates a new mock instance.
func NewMockCarsServiceClient(ctrl *gomock.Controller) *MockCarsServiceClient {
	mock := &MockCarsServiceClient{ctrl: ctrl}
	mock.recorder = &MockCarsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarsServiceClient) EXPECT() *MockCarsServiceClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCarsServiceClient) Get(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*Car, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCarsServiceClientMockRecorder) Get(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCarsServiceClient)(nil).Get), varargs...)
}

// MockCarsServiceServer is a mock of CarsServiceServer interface.
type MockCarsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCarsServiceServerMockRecorder
}

// MockCarsServiceServerMockRecorder is the mock recorder for MockCarsServiceServer.
type MockCarsServiceServerMockRecorder struct {
	mock *MockCarsServiceServer
}

// NewMockCarsServiceServer creates a new mock instance.
func NewMockCarsServiceServer(ctrl *gomock.Controller) *MockCarsServiceServer {
	mock := &MockCarsServiceServer{ctrl: ctrl}
	mock.recorder = &MockCarsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarsServiceServer) EXPECT() *MockCarsServiceServerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCarsServiceServer) Get(arg0 context.Context, arg1 *GetCarRequest) (*Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCarsServiceServerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCarsServiceServer)(nil).Get), arg0, arg1)
}

// mustEmbedUnimplementedCarsServiceServer mocks base method.
func (m *MockCarsServiceServer) mustEmbedUnimplementedCarsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCarsServiceServer")
}

// mustEmbedUnimplementedCarsServiceServer indicates an expected call of mustEmbedUnimplementedCarsServiceServer.
func (mr *MockCarsServiceServerMockRecorder) mustEmbedUnimplementedCarsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCarsServiceServer", reflect.TypeOf((*MockCarsServiceServer)(nil).mustEmbedUnimplementedCarsServiceServer))
}

// MockUnsafeCarsServiceServer is a mock of UnsafeCarsServiceServer interface.
type MockUnsafeCarsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCarsServiceServerMockRecorder
}

// MockUnsafeCarsServiceServerMockRecorder is the mock recorder for MockUnsafeCarsServiceServer.
type MockUnsafeCarsServiceServerMockRecorder struct {
	mock *MockUnsafeCarsServiceServer
}

// NewMockUnsafeCarsServiceServer creates a new mock instance.
func NewMockUnsafeCarsServiceServer(ctrl *gomock.Controller) *MockUnsafeCarsServiceServer {
	mock := &MockUnsafeCarsServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCarsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCarsServiceServer) EXPECT() *MockUnsafeCarsServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCarsServiceServer mocks base method.
func (m *MockUnsafeCarsServiceServer) mustEmbedUnimplementedCarsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCarsServiceServer")
}

// mustEmbedUnimplementedCarsServiceServer indicates an expected call of mustEmbedUnimplementedCarsServiceServer.
func (mr *MockUnsafeCarsServiceServerMockRecorder) mustEmbedUnimplementedCarsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCarsServiceServer", reflect.TypeOf((*MockUnsafeCarsServiceServer)(nil).mustEmbedUnimplementedCarsServiceServer))
}
