// Code generated by MockGen. DO NOT EDIT.
// Source: cars_grpc.pb.go

// Package carsapi is a generated GoMock package.
package carsapi

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCarsClient is a mock of CarsClient interface.
type MockCarsClient struct {
	ctrl     *gomock.Controller
	recorder *MockCarsClientMockRecorder
}

// MockCarsClientMockRecorder is the mock recorder for MockCarsClient.
type MockCarsClientMockRecorder struct {
	mock *MockCarsClient
}

// NewMockCarsClient creates a new mock instance.
func NewMockCarsClient(ctrl *gomock.Controller) *MockCarsClient {
	mock := &MockCarsClient{ctrl: ctrl}
	mock.recorder = &MockCarsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarsClient) EXPECT() *MockCarsClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCarsClient) Get(ctx context.Context, in *GetCarRequest, opts ...grpc.CallOption) (*Car, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCarsClientMockRecorder) Get(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCarsClient)(nil).Get), varargs...)
}

// MockCarsServer is a mock of CarsServer interface.
type MockCarsServer struct {
	ctrl     *gomock.Controller
	recorder *MockCarsServerMockRecorder
}

// MockCarsServerMockRecorder is the mock recorder for MockCarsServer.
type MockCarsServerMockRecorder struct {
	mock *MockCarsServer
}

// NewMockCarsServer creates a new mock instance.
func NewMockCarsServer(ctrl *gomock.Controller) *MockCarsServer {
	mock := &MockCarsServer{ctrl: ctrl}
	mock.recorder = &MockCarsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarsServer) EXPECT() *MockCarsServerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCarsServer) Get(arg0 context.Context, arg1 *GetCarRequest) (*Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCarsServerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCarsServer)(nil).Get), arg0, arg1)
}

// mustEmbedUnimplementedCarsServer mocks base method.
func (m *MockCarsServer) mustEmbedUnimplementedCarsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCarsServer")
}

// mustEmbedUnimplementedCarsServer indicates an expected call of mustEmbedUnimplementedCarsServer.
func (mr *MockCarsServerMockRecorder) mustEmbedUnimplementedCarsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCarsServer", reflect.TypeOf((*MockCarsServer)(nil).mustEmbedUnimplementedCarsServer))
}

// MockUnsafeCarsServer is a mock of UnsafeCarsServer interface.
type MockUnsafeCarsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCarsServerMockRecorder
}

// MockUnsafeCarsServerMockRecorder is the mock recorder for MockUnsafeCarsServer.
type MockUnsafeCarsServerMockRecorder struct {
	mock *MockUnsafeCarsServer
}

// NewMockUnsafeCarsServer creates a new mock instance.
func NewMockUnsafeCarsServer(ctrl *gomock.Controller) *MockUnsafeCarsServer {
	mock := &MockUnsafeCarsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCarsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCarsServer) EXPECT() *MockUnsafeCarsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCarsServer mocks base method.
func (m *MockUnsafeCarsServer) mustEmbedUnimplementedCarsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCarsServer")
}

// mustEmbedUnimplementedCarsServer indicates an expected call of mustEmbedUnimplementedCarsServer.
func (mr *MockUnsafeCarsServerMockRecorder) mustEmbedUnimplementedCarsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCarsServer", reflect.TypeOf((*MockUnsafeCarsServer)(nil).mustEmbedUnimplementedCarsServer))
}
