// Code generated by protoc-gen-go-client-constructor. DO NOT EDIT.
//
// Version: v1.10.0
//---------------------------------------------------

//go:generate mockgen -source=cars_grpc.pb.go -package=carsapi -destination=cars_grpc.pb.mock.go

package carsapi

import (
	"fmt"
	"net"

	gomock "github.com/golang/mock/gomock"
	"google.golang.org/grpc"
)

type MockClient struct {
	Client          *Client
	recorder        *MockClientMockRecorder
	MockCarsService *MockCarsServiceClient
}

type MockClientMockRecorder struct {
	*MockCarsServiceClientMockRecorder
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mockClient := &MockClient{
		MockCarsService: NewMockCarsServiceClient(ctrl),
	}

	mockClient.recorder = &MockClientMockRecorder{
		MockCarsServiceClientMockRecorder: mockClient.MockCarsService.recorder,
	}

	mockClient.Client = &Client{
		conn:              nil,
		CarsServiceClient: mockClient.MockCarsService,
	}

	return mockClient
}

func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

type MockServer struct {
	CarsService *MockCarsServiceServer
	Server      *grpc.Server
	Listener    net.Listener
}

func (m *MockServer) Close() error {
	m.Server.GracefulStop()
	return m.Listener.Close()
}

func NewMockServer(ctrl *gomock.Controller, cfg *Config, opts ...grpc.ServerOption) (*MockServer, error) {
	s := &MockServer{
		Server:      grpc.NewServer(opts...),
		CarsService: NewMockCarsServiceServer(ctrl),
	}

	l, err := net.Listen("tcp", cfg.Host)
	if err != nil {
		return nil, fmt.Errorf("failed to listen tcp %s: %w", cfg.Host, err)
	}

	s.Listener = l
	RegisterCarsServiceServer(s.Server, s.CarsService)
	return s, nil
}
