// Code generated by protoc-gen-go-client-constructor. DO NOT EDIT.
//
// Version: v1.10.0
//---------------------------------------------------

//go:generate mockgen -source=cars_grpc.pb.go -package=carsapi -destination=cars_grpc.pb.mock.go

package carsapi

import (
	"fmt"
	"net"

	gomock "github.com/golang/mock/gomock"
	"google.golang.org/grpc"
)

type MockClient struct {
	Client   *Client
	recorder *MockClientMockRecorder
	MockCars *MockCarsClient
}

type MockClientMockRecorder struct {
	*MockCarsClientMockRecorder
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mockClient := &MockClient{
		MockCars: NewMockCarsClient(ctrl),
	}

	mockClient.recorder = &MockClientMockRecorder{
		MockCarsClientMockRecorder: mockClient.MockCars.recorder,
	}

	mockClient.Client = &Client{
		conn:       nil,
		CarsClient: mockClient.MockCars,
	}

	return mockClient
}

func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

type MockServer struct {
	Cars     *MockCarsServer
	Server   *grpc.Server
	Listener net.Listener
}

func (m *MockServer) Close() error {
	m.Server.GracefulStop()
	return m.Listener.Close()
}

func NewMockServer(ctrl *gomock.Controller, cfg *Config, opts ...grpc.ServerOption) (*MockServer, error) {
	s := &MockServer{
		Server: grpc.NewServer(opts...),
		Cars:   NewMockCarsServer(ctrl),
	}

	l, err := net.Listen("tcp", cfg.Host)
	if err != nil {
		return nil, fmt.Errorf("failed to listen tcp %s: %w", cfg.Host, err)
	}

	s.Listener = l
	RegisterCarsServer(s.Server, s.Cars)
	return s, nil
}
