databases:
  default:
    driver: postgres
    dsn: ${PG_DSN}

tasks:
  dump-migrations:
    activities:
      - export: json-schema
        spec:
          pretty: true
        out:
          dir: ./out

  gen-entities:
    activities:
      - export: go-entity-repository
        skip_exists: true
        spec:
          entities:
            package: internal/domain
          repositories:
            package: internal/infrastructure/repository
            container:
              struct_name: group
            interfaces:
              place: entity
        out:
          dir: ./

  ci-gen-docs:
    commit:
      message: "chore: generate documentation for database schema"
      push: true
    activities:
      - export: md
        spec:
          with_diagram: true
        out:
          dir: ./docs

  gen-docs:
    activities:
      - export: md
        spec:
          with_diagram: true
        out:
          dir: ./docs

options:
  print_stat: true
  debug: true
