services:
  cars-grpc:
    image: golang:1.21.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      CARS_LOG_LEVEL: debug
      CARS_DB_DSN: "host=postgres user=root password=root dbname=cars sslmode=disable"
      CARS_GRPC_PORT: 8000
      CARS_GRPC_USE_REFLECTION: true
    ports:
      - 8081:8000
    command:
      - go
      - run
      - ./cmd/grpc/main.go

  cars-http:
    image: golang:1.21.0-alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      CARS_LOG_LEVEL: debug
      CARS_DB_DSN: "host=postgres user=root password=root dbname=cars sslmode=disable"
      CARS_HTTP_PORT: 8000
    ports:
      - 8080:8000
    command:
      - go
      - run
      - ./cmd/http/main.go

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "cars"
    ports:
      - "5430:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  migrations:
    image: artsafin/goose-migrations
    volumes:
      - ./migrations:/migrations
    command:
      - postgres
      - "host=postgres user=root password=root dbname=cars sslmode=disable"
      - up
    links:
      - postgres

volumes:
  postgres: {}
