swagger: "2.0"
info:
  title: Example service
  description: Example service
  version: 0.0.1
host: localhost
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /cars/{id}:
    get:
      description: "Get Car"
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/car-get-response"
        500:
          description: "success"
          schema:
            $ref: "#/definitions/error-response"

definitions:
  car-get-response:
    description: "Car"
    properties:
      id:
        type: integer

  error-response:
    description: "Error"
    properties:
      message:
        type: string
