// Code generated by go-swagger; DO NOT EDIT.

package app

import (
	"github.com/caarlos0/env/v10"
	"github.com/pkg/errors"

	"github.com/artarts36/go-service-template/internal/config"
)

// Config struct
type Config struct {
	config.Config

	HTTP HTTPConfig `envPrefix:"HTTP_"`
}

type HTTPConfig struct {
	Port int `env:"PORT,required"`
}

// InitConfig func
func InitConfig(prefix string) (*Config, error) {
	config := &Config{}
	opts := env.Options{
		Prefix: prefix,
	}

	if err := env.ParseWithOptions(config, opts); err != nil {
		return nil, errors.Wrap(err, "init config failed")
	}

	return config, nil
}
