name: Generate documentation

permissions: write-all

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: cars
        ports:
          - 5499:5432

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: 1.21.0

      - name: Install migrator
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations
        env:
          GOOSE_MIGRATION_DIR: './migrations'
        run: goose postgres "host=localhost port=5499 user=test password=test dbname=cars sslmode=disable" up

      - name: Generate markdown docs
        uses: artarts36/db-exporter@master
        with:
          tasks: ci-gen-docs
